import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        background: "#f7f9fb",
        "on-background": "#191c1e",
        surface: "#f7f9fb",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "on-surface-variant": "#45474c",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "surface-tint": "#545f73",
        primary: "#1e293b",
        "primary-container": "#1e293b",
        "on-primary": "#ffffff",
        "on-primary-container": "#8590a6",
        "primary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#bcc7de",
        "on-primary-fixed": "#111c2d",
        "on-primary-fixed-variant": "#3c475a",
        "inverse-primary": "#bcc7de",
        secondary: "#505f76",
        "secondary-container": "#d0e1fb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54647a",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        outline: "#75777d",
        "outline-variant": "#c5c6cd",
        neutral: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
        },
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
      },
      fontSize: {
        "display-lg": [
          "30px",
          {
            lineHeight: "38px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "20px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "title-sm": [
          "16px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0",
            fontWeight: "400",
          },
        ],
        "body-sm": [
          "13px",
          {
            lineHeight: "18px",
            letterSpacing: "0",
            fontWeight: "400",
          },
        ],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "container-margin": "40px",
        gutter: "20px",
      },
    },
  },
  plugins: [],
} satisfies Config;
